### ISSUE TITLE
Support for data proxy

### ISSUE THREAD

**Issue by RobertUpchurch** [danieluhm2004/serverless-webpack-prisma#16]
I might be misunderstanding the need for this library when using a data proxy. 

From my understanding building with a data proxy makes it so that the engine runtimes do not need to be included in the webpack. However im not sure if that completely removes the need for this library. 

If there is still benefit in this library, how would i get it to support running --data-proxy when it generates the prisma client?

**Comment by RobertUpchurch** [comment]
I opened a PR with a small fix that works for me locally. Hopefully this can get merged in so i can use it seamlessly in my CI/CD.

danieluhm2004/serverless-webpack-prisma#17

**Comment by RobertUpchurch** [comment]
Needing an NPM release to update the PR that was merged.

**Comment by danieluhm2004** [comment]
I will update soon.
Thank you :)

**Comment by danieluhm2004** [comment]
v1.1.1 has been published! 👋
