### ISSUE TITLE
Feature request: Ability to symlink prisma schema and ability to ignore functions

### ISSUE THREAD

**Issue by rostislav-simonik** [danieluhm2004/serverless-webpack-prisma#23]
# Ability to symlink prisma folder. 

In our projects, we are sharing prisma schema through the installed package. And we are symlinking it to repo root. 

`copyPrismaSchemaToFunction` will copy the symlink instead of the folder itself, and obviously in packaging given symlink points to the wrong (non-existing location). It would be great to be able to symlink a given folder instead of copying it. 

# Ability to ignore functions 

If serverless config is configured to package functions individually, then not every function in our project is prisma based, That will resulting packaging failure, because of missing prisma files. Would be great to have the ability to specify which functions can be ignored.

**Comment by danieluhm2004** [comment]
Thank you for your pull request!
