### ISSUE TITLE
plugin is installing latest prisma version

### ISSUE THREAD

**Issue by bmaciass** [danieluhm2004/serverless-webpack-prisma#25]
Currently, we are using the module to remove unused prisma deps, but our prisma schema was developed using v3.13.0 but this plugin is installing the latest prisma module. We're using yarn3.

We're going to update our prisma to v4 but anyways it would be great to support adding a version.

**Comment by danieluhm2004** [comment]
This is has been solved at #29. You can use solved package in v1.2.0! Thank you.
