### ISSUE TITLE
Prisma 5 will rename `migration-engine` to `schema-engine`

### ISSUE THREAD

**Issue by janpio** [danieluhm2004/serverless-webpack-prisma#28]
Heads up, soon there will be a Prisma 5 release that will change the naming of the Migration to Schema Engine, which will also affect the filenames. You can probably add this new name to your list of files to remove.

**Comment by Tybot204** [comment]
Connecting this PR that resolves this issue: https://github.com/danieluhm2004/serverless-webpack-prisma/pull/30

Any chance @danieluhm2004 can review please? It looks like a straight forward addition from the Prisma docs. Docs for reference: https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-5#example-with-the-serverless-framework

**Comment by danieluhm2004** [comment]
Thank you.

This issue has been solved in v1.2.0!
