### ISSUE TITLE
Schema dir param

### ISSUE THREAD

**Issue by pcrodrigues0** [danieluhm2004/serverless-webpack-prisma#5]
My project uses a monorepo managed by lerna. So i'm using the same schema.prisma in various serverless.yml files. I'm trying to find a way to use the param --schema param on the process to generate the schema.

**Comment by danieluhm2004** [comment]
Hello @pcrodrigues0.

first, thank you for being interesting in my project.

You using Lerna for monorepo. So you need to choose the path of the schema file.

If We add the schema path option in ``serverless.yml``. It will resolve the problem?

Thank you

**Comment by pcrodrigues0** [comment]
Hi @danieluhm2004, thanks for the short answer. Definitely will solve my problem here.

Thanks 😃

**Comment by pcrodrigues0** [comment]
Hello again @danieluhm2004 i'll send a pull request in a few minutes that fixes this problem and another that i found here.

Tried to find you on discord but didn't found the user :/

**Comment by pcrodrigues0** [comment]
@danieluhm2004 PR https://github.com/danieluhm2004/serverless-webpack-prisma/pull/6 is opened, this will definitely solve all my problems with the package, i think theres a lot of things that can be improved and inserted in your project, congrats for building this.

I'll send more PR's 😄

**Comment by danieluhm2004** [comment]
We will continue with that pull request.

Thank you. :)
