### ISSUE TITLE
Prisma Generate Package Individually Only if In Use

### ISSUE THREAD

**Issue by masanaikeshima** [danieluhm2004/serverless-webpack-prisma#8]
This plugins working great and the following is more of a query/request:

Currently we have a few lambdas, some of which don't use Prisma. If we use the option in serverless.yml:

`
package: 
    individually: true
`

This leads to each function having the Prisma Generate script running (understandably as they are built in isolation).  However a completely basic lambda that simply console.logs("Hello world") seems to still load in Prisma and results in the size for the function around 35MB.

Is there a way for functions that don't use Prisma to skip this process so we can reduce the Prisma footprint?

**Comment by mcrstudio** [comment]
Yeah this would be fantastic.

**Comment by ekarmazin** [comment]
Still an issue with functions which are not require prisma. Why this issue was closed with no details? Any workaround for this?
